name: Build and Push Docker Image

on:
  push:
    tags:
      - '^v\d+\.\d+\.\d+(-\w+)?$'

#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

env:
  IMAGE_NAME: frontend-mailgun-proxy
  IMAGE_TAG: ${{ github.ref#refs/tags/ }} # eg. v0.0.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file ./.docker/Dockerfile --tag $IMAGE_NAME --label $IMAGE_TAG
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Add tag to image
        run: docker tag $IMAGE_NAME ghcr.io/m-mattia-m/$IMAGE_NAME:$IMAGE_TAG
      - name: Push image to container-registry
        run: docker push ghcr.io/m-mattia-m/$IMAGE_NAME:$IMAGE_TAG